[features]
seeds = false
[programs.devnet]
whitelist = "Dc7ZTiYiq1tuVnkkuuCMSVNgVaWacABFxppKEsqh5DJb"
counter = "7xDHuz7n9Sp6ck9vbrSE1weXYj2rxaREw3RbAAdJ39zK"
minter = "HmjebbJ7FpFsjg28kn1jT8LKoA4JXKi597581ct7YeFY"
[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
whitelist = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/whitelist.ts"
counter = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/counter.ts"
minter = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/minter.ts"
backend = "yarn run ts-mocha -p ./tsconfig.json backend/backend.ts"

