[features]
seeds = false
[programs.devnet]
whitelist = "EpsbCmDJTV9XHKmeoJb1bQNUtfw6rEKVuGiDXUXJ6YS8"
counter = "BAkJm4eDSRr6Rn1xeu8kxXnuD46B1iNTz2fPF9NK8sDh"
minter = "FtT5WYN8aHk2g9cZezcsLkAxXhHhkgYfBchrMJynsNo1"
[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
whitelist = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/whitelist.ts"
counter = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/counter.ts"
minter = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/minter.ts"
backend = "yarn run ts-mocha -p ./tsconfig.json backend/backend.ts"

